setup: &SETUP
  env:
    HOME: /tmp # cargo needs it
  setup_script:
    - pkg install -y llvm
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal
    - $HOME/.cargo/bin/rustup toolchain install $VERSION

task:
  env:
    HOME: /tmp  # cargo cache needs it
    TARGET: x86_64-unknown-freebsd
    VERSION: nightly
  matrix:
    - name: FreeBSD 13 amd64 nightly
      freebsd_instance:
        image: freebsd-13-3-release-amd64
    - name: FreeBSD 14 amd64 nightly
      freebsd_instance:
        image: freebsd-14-1-release-amd64-ufs
    - name: FreeBSD 13 amd64 stable
      env:
        VERSION: 1.81.0
      freebsd_instance:
        image: freebsd-13-3-release-amd64
    - name: FreeBSD 13 i686 nightly
      # Test i686 FreeBSD in 32-bit emulation on a 64-bit host.
      env:
        TARGET: i686-unknown-freebsd
      freebsd_instance:
        image: freebsd-13-3-release-amd64
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - if [ "$TARGET" = "i686-unknown-freebsd" ]; then rustup target add --toolchain $VERSION i686-unknown-freebsd; fi
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test --target $TARGET --no-default-features
    - cargo +$VERSION test --target $TARGET --all-features
  doc_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION doc --target $TARGET --no-deps --all-features
  before_cache_script: rm -rf $HOME/.cargo/registry/index 

# Stuff that doesn't need to be repeated for each target, env, and toolchain
lint_task:
  name: lint
  env:
    HOME: /tmp  # cargo cache needs it
    VERSION: nightly
  freebsd_instance:
    image: freebsd-13-3-release-amd64
  << : *SETUP
  extra_setup_script:
    - . $HOME/.cargo/env
    - rustup component add --toolchain $VERSION clippy
    - rustup component add --toolchain $VERSION rustfmt
    - pkg install -y ca_root_nss cargo-audit
  cargo_cache:
    folder: $HOME/.cargo/registry
  clippy_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION clippy --all-targets --no-default-features -- -D warnings
    - cargo +$VERSION clippy --all-targets --all-features -- -D warnings
  fmt_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION fmt --all -- --check --color=never
  audit_script:
    - . $HOME/.cargo/env
    - cargo audit
  minver_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION update -Zdirect-minimal-versions
    - cargo +$VERSION check --all-targets --all-features
  before_cache_script: rm -rf $CARGO_HOME/registry/index

# Ensure that the docs can be cross-compiled, as docs.rs does.
task:
  name: Cross docs
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  env:
    RUSTFLAGS: --cfg docsrs
    RUSTDOCFLAGS: --cfg docsrs
  doc_script:
    - rustup target add x86_64-unknown-freebsd
    - cargo doc --target x86_64-unknown-freebsd --no-deps --all-features
  before_cache_script: rm -rf $HOME/.cargo/registry/index
