#![allow(non_camel_case_types)]
use casper_sys::cap_channel_t;
use libc::sockaddr;
/* automatically generated by rust-bindgen 0.69.1 */

pub const CAPNET_BIND: u32 = 32;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __sa_family_t = __uint8_t;
pub type __socklen_t = __uint32_t;
pub type socklen_t = __socklen_t;
pub type cap_net_limit_t = u8;
extern "C" {
    pub fn cap_bind(
        chan: *mut cap_channel_t,
        s: ::std::os::raw::c_int,
        addr: *const sockaddr,
        addrlen: socklen_t,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_net_limit_init(
        chan: *mut cap_channel_t,
        mode: u64,
    ) -> *mut cap_net_limit_t;
}
extern "C" {
    pub fn cap_net_limit(limit: *mut cap_net_limit_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn cap_net_limit_bind(
        limit: *mut cap_net_limit_t,
        sa: *const sockaddr,
        salen: socklen_t,
    ) -> *mut cap_net_limit_t;
}
